<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><title>{{ $note->number }}</title><style>
@page{margin:30px 38px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#252525;font-size:11px}.header{width:100%;border-bottom:3px solid #2f2f2f;padding-bottom:15px}.header td{vertical-align:middle}.logo{width:85px}.brand{font-size:18px;font-weight:bold}.small{font-size:8px;color:#777;line-height:1.5}.title{text-align:right;font-size:22px;font-weight:bold;color:#bd2433}.number{text-align:right;color:#666}.meta{width:100%;margin:22px 0;border-collapse:separate;border-spacing:8px}.meta td{width:50%;vertical-align:top;border:1px solid #e5e5df;padding:12px}.label{font-size:8px;text-transform:uppercase;letter-spacing:1px;color:#999;font-weight:bold}.client{font-size:14px;font-weight:bold;margin:5px 0}.lines{width:100%;border-collapse:collapse}.lines th{background:#2f2f2f;color:white;text-align:left;padding:9px}.lines td{padding:10px 9px;border-bottom:1px solid #eaeae5}.qty{text-align:center;width:110px}.info{margin-top:18px;width:100%}.info td{vertical-align:top;width:50%;padding-right:12px}.box{background:#fafaf7;border-left:3px solid #fcf108;padding:12px;min-height:70px}.signature{max-width:240px;max-height:90px;margin-top:8px}.proof{max-width:250px;max-height:130px;margin-top:8px}.line{margin-top:42px;border-top:1px solid #555;padding-top:5px;text-align:center}.footer{position:fixed;bottom:-15px;left:0;right:0;border-top:1px solid #ddd;padding-top:7px;text-align:center;font-size:8px;color:#888}
</style></head><body>
<table class="header"><tr><td style="width:105px">@if($logoData)<img class="logo" src="{{ $logoData }}">@endif</td><td><div class="brand">{{ $company['name'] }}</div><div class="small">{{ $company['address'] }}<br>Tél. : {{ $company['contact'] }} · WhatsApp : {{ $company['whatsapp'] }}<br>{{ $company['email'] }}<br>NIF : {{ $company['nif'] }} · RCS : {{ $company['rcs'] }} · STAT : {{ $company['stat'] }}</div></td><td><div class="title">BON DE LIVRAISON</div><div class="number">N° {{ $note->number }}</div></td></tr></table>
<table class="meta"><tr><td><div class="label">Client et coordonnées</div><div class="client">{{ $note->client_name }}</div><div>{{ $note->client_number }}</div><div>{{ $note->client_contact }}</div><div>{{ $note->delivery_address }}</div></td><td><div class="label">Informations de livraison</div><div style="margin-top:5px"><strong>Commande :</strong> {{ $note->order_number }}</div><div><strong>Date :</strong> {{ \Carbon\Carbon::parse($note->delivered_at)->format('d/m/Y') }}</div><div><strong>Nombre de colis :</strong> {{ $note->package_count }}</div><div><strong>Statut :</strong> {{ ucfirst(str_replace('_',' ',$note->status)) }}</div></td></tr></table>
<table class="lines"><thead><tr><th>Produits livrés</th><th class="qty">Qté commandée</th><th class="qty">Qté livrée</th></tr></thead><tbody>@foreach($items as $item)<tr><td><strong>{{ $item->name }}</strong></td><td class="qty">{{ rtrim(rtrim(number_format((float)$item->ordered_quantity,3,',',' '),'0'),',') }}</td><td class="qty">{{ rtrim(rtrim(number_format((float)$item->delivered_quantity,3,',',' '),'0'),',') }}</td></tr>@endforeach</tbody></table>
<table class="info"><tr><td><div class="box"><div class="label">Observations</div><div style="margin-top:6px">{!! nl2br(e($note->observations?:'Aucune observation')) !!}</div></div></td><td><div class="box"><div class="label">Réceptionnaire</div><div class="client">{{ $note->receiver_name?:'Non renseigné' }}</div>@if($signatureData)<img class="signature" src="{{ $signatureData }}">@else<div class="line">Signature du réceptionnaire</div>@endif</div></td></tr></table>
@if($proofData)<div style="margin-top:16px"><div class="label">Preuve de livraison</div><img class="proof" src="{{ $proofData }}"></div>@endif
<div class="footer">{{ $company['name'] }} · Bon de livraison généré le {{ now()->format('d/m/Y à H:i') }} · {{ $note->number }}</div>
</body></html>
