import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { AlertTriangle, ArrowRight, Boxes, CircleDollarSign, FilePlus2, PackageCheck, Plus, Receipt, Ship, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const money=(value:number)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(value)+' Ar';
const compact=(value:number)=>new Intl.NumberFormat('fr-FR',{notation:'compact',maximumFractionDigits:1}).format(value);
const colors=['#BD2433','#FCF108','#2F2F2F','#6B7280','#16A34A','#F97316','#2563EB'];
const EmptyChart=({label}:{label:string})=><div className="grid h-full place-items-center text-center text-sm text-gray-400">{label}</div>;

export default function Dashboard({metrics,counts,chart,orderStatus,expenseCategories,topProducts}:{metrics:any;counts:any;chart:any[];orderStatus:any[];expenseCategories:any[];topProducts:any[]}){
 const cards=[['CA facturé',metrics.invoiced,'Ce mois',TrendingUp,'red'],['CA encaissé',metrics.received,'Ce mois',WalletCards,'yellow'],['Profit net',metrics.profit,'Après charges',CircleDollarSign,'charcoal'],['Solde de trésorerie',metrics.cash,'Disponible',Receipt,'green'],['Commission encaissée',metrics.commission,'Services',TrendingUp,'red'],['Dépenses business',metrics.business,'Ce mois',TrendingDown,'yellow']];
 return <AuthenticatedLayout header={<><p className="eyebrow">Vue d’ensemble</p><h1 className="page-title">Bonjour, voici votre activité</h1></>} action={<Link href="/modules/commandes/create" className="btn-primary"><Plus size={17}/>Nouvelle commande</Link>}>
  <Head title="Dashboard"/>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,note,Icon,tone]:any)=><div className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={20}/></div><div><p className="text-xs font-medium text-gray-500">{label}</p><strong className="mt-1 block text-xl">{money(value)}</strong><small className="text-[11px] text-gray-400">{note}</small></div></div>)}</div>

  <div className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
   <section className="panel"><div className="panel-head"><div><h2>Chiffre d’affaires</h2><p>Données réelles facturées et encaissées</p></div><span className="badge">6 derniers mois</span></div><div className="h-[290px] pt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#BD2433" stopOpacity={.22}/><stop offset="95%" stopColor="#BD2433" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false}/><Tooltip formatter={(value:any)=>money(Number(value))}/><Legend/><Area name="Facturé" type="monotone" dataKey="facture" stroke="#BD2433" fill="url(#revenue)" strokeWidth={2.5}/><Area name="Encaissé" type="monotone" dataKey="encaisse" stroke="#D6C900" fill="transparent" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></section>
   <section className="panel"><div className="panel-head"><div><h2>Actions urgentes</h2><p>À traiter aujourd’hui</p></div><span className="grid size-8 place-items-center rounded-lg bg-red-50 text-[#BD2433]"><AlertTriangle size={17}/></span></div><div className="divide-y divide-gray-100">{[[Ship,'Colis en transit',counts.shipments,'logistique'],[PackageCheck,'Commandes en cours',counts.orders,'commandes'],[Boxes,'Produits en stock faible',counts.lowStock,'stock']].map(([Icon,label,total,href]:any)=><Link href={'/modules/'+href} className="group flex items-center gap-3 py-4" key={label}><span className="grid size-10 place-items-center rounded-xl bg-[#F8F8F6] text-gray-600"><Icon size={18}/></span><span className="flex-1"><strong className="block text-sm">{label}</strong><small className="text-gray-400">{total} élément(s)</small></span><ArrowRight size={16} className="text-gray-300 group-hover:text-[#BD2433]"/></Link>)}</div></section>
  </div>

  <div className="mt-5 grid gap-5 xl:grid-cols-2">
   <section className="panel"><div className="panel-head"><div><h2>Flux de trésorerie</h2><p>Encaissements, sorties et résultat mensuel</p></div><span className="badge">6 mois</span></div><div className="h-[280px] pt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false}/><Tooltip formatter={(value:any)=>money(Number(value))}/><Legend/><Bar name="Encaissements" dataKey="encaisse" fill="#16A34A" radius={[6,6,0,0]}/><Bar name="Sorties" dataKey="depenses" fill="#BD2433" radius={[6,6,0,0]}/><Bar name="Résultat net" dataKey="net" fill="#FCF108" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section>
   <section className="panel"><div className="panel-head"><div><h2>Produits les plus commandés</h2><p>Classement par quantité commandée</p></div></div><div className="h-[280px] pt-5">{topProducts.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={topProducts} layout="vertical" margin={{left:15}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#eee"/><XAxis type="number" tickLine={false} axisLine={false}/><YAxis type="category" dataKey="name" width={120} tickLine={false} axisLine={false} tick={{fontSize:11}}/><Tooltip formatter={(value:any)=>[Number(value).toLocaleString('fr-FR'),'Quantité']}/><Bar dataKey="quantity" fill="#2F2F2F" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer>:<EmptyChart label="Les produits commandés apparaîtront ici."/>}</div></section>
  </div>

  <div className="mt-5 grid gap-5 xl:grid-cols-2">
   <section className="panel"><div className="panel-head"><div><h2>Commandes par statut</h2><p>Répartition de toutes les commandes actives</p></div></div><div className="h-[290px] pt-4">{orderStatus.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={orderStatus} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{orderStatus.map((_,index)=><Cell key={index} fill={colors[index%colors.length]}/>)}</Pie><Tooltip formatter={(value:any)=>[Number(value).toLocaleString('fr-FR'),'Commandes']}/><Legend verticalAlign="bottom"/></PieChart></ResponsiveContainer>:<EmptyChart label="Aucune commande disponible."/>}</div></section>
   <section className="panel"><div className="panel-head"><div><h2>Dépenses par catégorie</h2><p>Répartition des sorties du mois courant</p></div></div><div className="h-[290px] pt-4">{expenseCategories.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={expenseCategories} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{expenseCategories.map((_,index)=><Cell key={index} fill={colors[(index+2)%colors.length]}/>)}</Pie><Tooltip formatter={(value:any)=>money(Number(value))}/><Legend verticalAlign="bottom"/></PieChart></ResponsiveContainer>:<EmptyChart label="Aucune dépense pour ce mois."/>}</div></section>
  </div>

  <section className="mt-5 panel"><div className="panel-head"><div><h2>Raccourcis</h2><p>Enregistrez rapidement une opération</p></div></div><div className="grid gap-3 pt-4 sm:grid-cols-2 lg:grid-cols-4">{[[PackageCheck,'Créer une commande','commandes'],[FilePlus2,'Créer un devis','devis'],[WalletCards,'Saisir un paiement','paiements'],[Receipt,'Ajouter une dépense','depenses']].map(([Icon,label,href]:any)=><Link href={`/modules/${href}/create`} className="quick" key={label}><Icon size={20}/><span>{label}</span><ArrowRight size={15} className="ml-auto"/></Link>)}</div></section>
 </AuthenticatedLayout>;
}
