import BrandLogo from '@/Components/BrandLogo';
import PremiumDatePicker from '@/Components/PremiumDatePicker';
import PremiumMonthPicker from '@/Components/PremiumMonthPicker';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Eye, FileCheck2, Plus, Save, Star, Trash2, UserMinus, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

type Option={value:string|number;label:string;contact?:string;address?:string;type?:string;credit_balance?:number};
type Field={name:string;label:string;type:string;required:boolean;default?:string|number|null;preview?:string|null;options?:Option[]};
const money=(value:any)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(Number(value||0))+' Ar';
const isMoneyField=(field:Field)=>field.type==='number'&&field.label.includes('(Ar)');
const estimatedItemCost=(item:Record<string,any>)=>Number(item.supplier_price||0)*Number(item.quantity||0)+Number(item.china_delivery||0)+Number(item.packaging||0)+Number(item.freight||0);
const saleItemPrice=(item:Record<string,any>)=>estimatedItemCost(item)+Number(item.margin||0)+Number(item.commission||0);

export default function Form({module,config,fields,recordId,prefill={},itemFields=[],initialItems=[],initialPackages=[],initialSupplierProducts=null,orderProducts={},orderTemplates={},quoteTemplates={},company={}}:{module:string;config:any;fields:Field[];recordId?:number;prefill?:Record<string,any>;itemFields?:Field[];initialItems?:Record<string,any>[];initialPackages?:Record<string,any>[];initialSupplierProducts?:Record<string,any>[]|null;orderProducts?:Record<string,any[]>;orderTemplates?:Record<string,any>;quoteTemplates?:Record<string,any>;company?:Record<string,string>}){
 const normalizedItems=module==='devis'?initialItems.map(item=>({...item,total:saleItemPrice(item)})):initialItems;
 const initial={...Object.fromEntries(fields.map(field=>[field.name,field.type==='file'?null:field.default??''])),...prefill,...(itemFields.length?{items:normalizedItems}:{}),...(module==='commandes'?{packages:initialPackages,client_contact:''}:{}),...(!recordId&&['commandes','paiements'].includes(module)?{new_client_name:'',new_client_contact:'',new_client_type:'particulier',new_client_address:''}:{}),...(module==='fournisseurs'?{products:initialSupplierProducts||[]}:{}),...(recordId?{_method:'put'}:{})};
 const {data,setData,post,delete:destroy,processing,errors}=useForm<Record<string,any>>(initial);
 const [preview,setPreview]=useState(false);
 const [quickClient,setQuickClient]=useState(false);
 const previewable=['devis','commandes','factures'].includes(module);
 const paymentUnlinked=module==='paiements'&&!data.order_id&&!data.invoice_id;
 const paymentClient=module==='paiements'?fields.find(field=>field.name==='client_id')?.options?.find(option=>String(option.value)===String(data.client_id)):undefined;
 const clientFieldLocked=(field:Field)=>module==='devis'&&!!data.client_id&&['client_name','client_contact','client_type'].includes(field.name);
 const selectedOrderProducts=orderProducts[String(data.order_id)]||[];
 const persist=()=>post(recordId?`/modules/${module}/${recordId}`:`/modules/${module}`,{preserveScroll:true,forceFormData:true,onError:()=>setPreview(false)});
 const submit=(event:FormEvent)=>{event.preventDefault();previewable?setPreview(true):persist();};
 const labelFor=(name:string)=>{const field=fields.find(item=>item.name===name);return field?.options?.find(option=>String(option.value)===String(data[name]))?.label||data[name]||'—';};
 const addItem=()=>setData('items',[...(data.items||[]),Object.fromEntries(itemFields.map(field=>[field.name,field.name==='quantity'?1:field.type==='number'?0:'']))]);
 const updateItem=(index:number,name:string,value:any)=>setData('items',(data.items||[]).map((item:any,itemIndex:number)=>{if(itemIndex!==index)return item;const next={...item,[name]:value};return module==='devis'?{...next,total:saleItemPrice(next)}:next;}));
 const changeItem=(index:number,field:Field,value:any)=>{if(field.name!=='supplier_id'){updateItem(index,field.name,value);return;}const option=field.options?.find(item=>String(item.value)===String(value));setData('items',(data.items||[]).map((item:any,itemIndex:number)=>itemIndex===index?{...item,supplier_id:value,supplier_name:option?.label||item.supplier_name||'',supplier_contact:option?.contact||item.supplier_contact||''}:item));};
 const changeField=(field:Field,value:any)=>{
  if(module==='devis'&&field.name==='client_id'){const option=field.options?.find(item=>String(item.value)===String(value));setData((current:Record<string,any>)=>({...current,client_id:value,client_name:option?.label||'',client_contact:option?.contact||'',client_type:option?.type||'particulier'}));return;}
  if(module==='commandes'&&field.name==='client_id'){const option=field.options?.find(item=>String(item.value)===String(value));setData((current:Record<string,any>)=>({...current,client_id:value,client_contact:option?.contact||''}));return;}
  if(module==='paiements'&&field.name==='client_id'){setData((current:Record<string,any>)=>({...current,client_id:value,new_client_name:'',new_client_contact:'',new_client_type:'particulier',new_client_address:''}));return;}
  if(module==='commandes'&&field.name==='quote_id'&&value){const quote=quoteTemplates[String(value)];if(quote)setData((current:Record<string,any>)=>({...current,quote_id:value,client_id:quote.client_id,client_contact:quote.client_contact||'',shipping_mode:quote.shipping_mode||current.shipping_mode,items:quote.items,packages:[],new_client_name:'',new_client_contact:''}));return;}
  if(module==='factures'&&field.name==='order_id'&&value){const order=orderTemplates[String(value)];if(order){const paid=Number(order.paid_amount||0),total=Number(order.subtotal||0);setData((current:Record<string,any>)=>({...current,order_id:value,subtotal:total,paid_amount:paid,status:paid>=total?'payee':paid>0?'partielle':'brouillon'}));return;}}
  if(module==='paiements'&&['order_id','invoice_id'].includes(field.name)){setData((current:Record<string,any>)=>{const next={...current,[field.name]:value};if(!next.order_id&&!next.invoice_id)next.allocated_amount=0;return next;});return;}
  setData(field.name,value);
 };
 const removeItem=(index:number)=>{if((data.items||[]).length>1){setData('items',data.items.filter((_:any,itemIndex:number)=>itemIndex!==index));if(module==='commandes')setData('packages',(data.packages||[]).map((pack:any)=>({...pack,items:(pack.items||[]).filter((line:any)=>Number(line.item_index)!==index).map((line:any)=>({...line,item_index:Number(line.item_index)>index?Number(line.item_index)-1:Number(line.item_index)}))})).filter((pack:any)=>pack.items.length));}};
 return <AuthenticatedLayout header={<><Link href={`/modules/${module}`} className="mb-3 inline-flex items-center gap-2 text-xs font-semibold text-gray-400 hover:text-[#BD2433]"><ArrowLeft size={14}/>Retour à la liste</Link><p className="eyebrow">{recordId?'Correction':'Nouvel enregistrement'}</p><h1 className="page-title">{config.primary}</h1><p className="mt-1 text-sm text-gray-400">Les champs marqués d’un astérisque sont obligatoires.</p></>}>
  <Head title={config.primary}/>
  <form onSubmit={submit}>
   <section className="panel"><div className="grid gap-x-5 gap-y-5 md:grid-cols-2">{fields.map(field=><div key={field.name} className={field.type==='textarea'?'md:col-span-2':''}>
    <div className="mb-2 flex items-center justify-between gap-3"><label htmlFor={field.name} className="block text-xs font-semibold text-gray-600">{field.label}{(field.required||(module==='paiements'&&field.name==='notes'&&data.type==='autre'))&&!(['commandes','paiements'].includes(module)&&field.name==='client_id'&&quickClient)&&<span className="ml-1 text-[#BD2433]">*</span>}</label>{field.name==='employee_id'&&<Link href="/modules/employes/create" className="text-[11px] font-semibold text-[#BD2433] hover:underline">+ Ajouter un employé</Link>}{['commandes','paiements'].includes(module)&&field.name==='client_id'&&!recordId&&<button type="button" onClick={()=>{setQuickClient(!quickClient);if(!quickClient)setData('client_id','');else setData((current:Record<string,any>)=>({...current,new_client_name:'',new_client_contact:'',new_client_type:'particulier',new_client_address:''}));}} className="text-[11px] font-semibold text-[#BD2433] hover:underline">{quickClient?'Choisir un client existant':'+ Nouveau client ici'}</button>}</div>
    {['commandes','paiements'].includes(module)&&field.name==='client_id'&&quickClient?<QuickClientFields data={data} errors={errors} setData={setData} context={module}/>:field.name==='quality_rating'?<PremiumStarRating value={Number(data[field.name]||0)} onChange={value=>setData(field.name,value)}/>:field.type==='select'?<select id={field.name} value={data[field.name]} onChange={event=>changeField(field,event.target.value)} className="field disabled:cursor-not-allowed disabled:bg-gray-100 disabled:text-gray-500" disabled={clientFieldLocked(field)} required={field.required&&!(['commandes','paiements'].includes(module)&&field.name==='client_id'&&quickClient)}><option value="">{module==='depenses'&&field.name==='order_id'?'Aucune — charge générale':module==='paiements'&&['order_id','invoice_id'].includes(field.name)?'Aucune — crédit sur le compte client':'Sélectionner…'}</option>{field.options?.map(option=><option key={String(option.value)} value={option.value}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea id={field.name} value={data[field.name]} onChange={event=>setData(field.name,event.target.value)} className="field min-h-24" required={field.required||(module==='paiements'&&field.name==='notes'&&data.type==='autre')}/>:field.type==='file'?<div className="flex items-center gap-3">{field.preview&&<img src={field.preview} alt="Photo actuelle" className="size-16 rounded-xl border border-gray-200 object-cover"/>}<input id={field.name} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setData(field.name,event.target.files?.[0]??null)} className="field file:mr-3 file:rounded-lg file:border-0 file:bg-[#FCF108] file:px-3 file:py-1.5 file:text-xs file:font-semibold" required={field.required}/></div>:field.type==='date'?<PremiumDatePicker value={data[field.name]} onChange={value=>setData(field.name,value)} required={field.required}/>:field.type==='month'?<PremiumMonthPicker value={data[field.name]} onChange={value=>setData(field.name,value)} required={field.required}/>:isMoneyField(field)?<MoneyInput value={data[field.name]} onChange={value=>setData(field.name,value)} required={field.required} disabled={field.name==='allocated_amount'&&paymentUnlinked}/>:<input id={field.name} type={field.type} step={field.type==='number'?'0.01':undefined} min={field.type==='number'?0:undefined} value={data[field.name]} onChange={event=>setData(field.name,event.target.value)} className="field disabled:cursor-not-allowed disabled:bg-gray-100 disabled:text-gray-500" disabled={clientFieldLocked(field)} required={field.required}/>}<></>
    {errors[field.name]&&<p className="mt-1.5 text-xs font-medium text-[#BD2433]">{errors[field.name]}</p>}
    {clientFieldLocked(field)&&<p className="mt-1.5 text-[11px] text-gray-400">Complété automatiquement depuis la fiche client.</p>}
    {module==='paiements'&&field.name==='client_id'&&paymentClient&&<p className="mt-1.5 text-[11px] font-semibold text-[#817900]">Solde client actuel : {money(paymentClient.credit_balance||0)}</p>}
    {module==='depenses'&&field.name==='order_id'&&<p className={`mt-2 text-xs ${data.order_id?'text-[#817900]':'text-gray-400'}`}>{data.order_id?'Cette dépense sera affectée au coût et à la rentabilité de cette commande.':'Laissez vide pour un loyer ou une autre charge générale de l’entreprise.'}</p>}
   </div>)}</div>
    {module==='fournisseurs'&&<SupplierProductEditor products={data.products||[]} errors={errors} onChange={products=>setData('products',products)}/>} 
    {['factures','logistique'].includes(module)&&data.order_id&&<OrderProductGallery products={selectedOrderProducts} context={module==='factures'?'facture':'suivi logistique'}/>} 
    {itemFields.length>0&&<div className="mt-8 border-t border-gray-100 pt-6">
     <div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-base font-bold">Produits / articles</h2><p className="text-xs text-gray-400">Ajoutez chaque produit ou article avec sa quantité, ses caractéristiques et ses informations commerciales.</p></div><button type="button" onClick={addItem} className="btn-secondary"><Plus size={16}/>Ajouter un produit / article</button></div>
     <div className="space-y-4">{(data.items||[]).map((item:any,index:number)=><div key={index} className="rounded-xl border border-gray-200 bg-[#FAFAF8] p-4">
      <div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3">{item.photo_url&&<img src={item.photo_url} alt="" className="size-14 rounded-xl border border-gray-200 object-cover"/>}<div><strong className="block text-sm">Produit / article {index+1}</strong><small className="text-[10px] text-gray-400">Informations de la ligne n° {index+1}</small>{item.photo instanceof File&&<small className="block text-[10px] text-emerald-600">Photo : {item.photo.name}</small>}</div></div><button type="button" onClick={()=>removeItem(index)} disabled={(data.items||[]).length===1} title="Retirer cette ligne" className="grid size-8 place-items-center rounded-lg text-gray-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-30"><Trash2 size={15}/></button></div>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{itemFields.map(field=><div key={field.name} className={field.type==='textarea'?'md:col-span-2 lg:col-span-3':''}><label className="mb-1.5 block text-xs font-semibold text-gray-600">{field.label}{field.required&&<span className="ml-1 text-[#BD2433]">*</span>}</label>{field.type==='select'?<select value={item[field.name]??''} onChange={event=>changeItem(index,field,event.target.value)} className="field" required={field.required}><option value="">Sélectionner…</option>{field.options?.map(option=><option key={String(option.value)} value={option.value}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea value={item[field.name]??''} onChange={event=>updateItem(index,field.name,event.target.value)} className="field min-h-36" required={field.required}/>:field.type==='file'?<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>updateItem(index,field.name,event.target.files?.[0]??null)} className="field file:mr-3 file:rounded-lg file:border-0 file:bg-[#FCF108] file:px-3 file:py-1.5 file:text-xs file:font-semibold" required={field.required}/>:isMoneyField(field)?<MoneyInput value={item[field.name]??''} onChange={value=>updateItem(index,field.name,value)} required={field.required} disabled={module==='devis'&&field.name==='total'}/>:<input type={field.type} step={field.type==='number'?'0.01':undefined} min={field.type==='number'?0:undefined} value={item[field.name]??''} onChange={event=>updateItem(index,field.name,event.target.value)} className="field" required={field.required}/>} {errors[`items.${index}.${field.name}`]&&<p className="mt-1 text-xs text-[#BD2433]">{errors[`items.${index}.${field.name}`]}</p>}{module==='devis'&&field.name==='freight'&&<div className="mt-3 rounded-xl border border-[#E5DB00] bg-[#FCF108]/15 p-3"><span className="block text-[10px] font-bold uppercase tracking-wider text-[#817900]">Total estimé</span><strong className="mt-1 block text-base text-[#2F2F2F]">{money(estimatedItemCost(item))}</strong></div>}</div>)}</div>
     </div>)}</div>
     <div className="ml-auto mt-4 max-w-sm rounded-xl bg-[#2F2F2F] p-4 text-white"><div className="flex justify-between text-sm"><span className="text-white/60">Total {module==='devis'?'du devis':'de la commande'}</span><strong>{money((data.items||[]).reduce((sum:number,item:any)=>sum+Number(item[module==='devis'?'total':'client_total']||0),0))}</strong></div></div>
    </div>}
    {module==='commandes'&&<PackageEditor packages={data.packages||[]} items={data.items||[]} errors={errors} onChange={packages=>setData('packages',packages)}/>} 
    {module==='paiements'&&<div className={`mt-6 rounded-xl border p-4 text-sm ${paymentUnlinked?'border-[#FCF108] bg-[#FCF108]/10 text-[#665f00]':'border-gray-200 bg-[#F8F8F6] text-gray-600'}`}><strong className="block">{paymentUnlinked?'Crédit client pour une future commande':'Paiement lié à un document'}</strong><p className="mt-1 text-xs leading-relaxed">{paymentUnlinked?`La totalité du montant reçu (${money(data.amount)}) sera ajoutée au compte du client et restera disponible pour une prochaine commande.`:`La partie non affectée du paiement sera conservée comme crédit disponible sur le compte client.`}</p></div>}
    <div className="mt-7 flex items-center justify-end gap-3 border-t border-gray-100 pt-5">{module==='employes'&&recordId&&<button type="button" onClick={()=>{if(window.confirm('Confirmer le départ de cet employé ? Son historique salarial sera conservé.'))destroy(`/modules/employes/${recordId}`);}} disabled={processing} className="mr-auto inline-flex items-center gap-2 rounded-[11px] border border-red-200 bg-white px-4 py-2.5 text-sm font-semibold text-red-600 hover:bg-red-50"><UserMinus size={17}/>Retirer de l’entreprise</button>}<Link href={`/modules/${module}`} className="btn-secondary">Annuler</Link><button type="submit" disabled={processing} className="btn-primary disabled:cursor-not-allowed disabled:opacity-60">{previewable?<Eye size={17}/>:<Save size={17}/>} {processing?'Enregistrement…':previewable?'Aperçu avant sauvegarde':recordId?'Enregistrer les corrections':'Enregistrer'}</button></div>
   </section>
  </form>
  {preview&&<div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-[#1f1f1f]/70 p-4 backdrop-blur-sm md:p-8" role="dialog" aria-modal="true" aria-label="Aperçu du document"><div className="w-full max-w-4xl overflow-hidden rounded-2xl bg-[#F5F5F2] shadow-2xl"><div className="flex items-center justify-between border-b border-gray-200 bg-white px-5 py-4"><div><strong className="text-sm">Aperçu avant sauvegarde</strong><p className="text-xs text-gray-400">Vérifiez soigneusement le document.</p></div><button onClick={()=>setPreview(false)} className="grid size-9 place-items-center rounded-lg text-gray-500 hover:bg-gray-100" aria-label="Fermer"><X size={18}/></button></div><div className="p-4 md:p-8"><div className="relative min-h-[560px] bg-white p-7 shadow-sm md:p-10"><span className="absolute right-8 top-8 rounded-full bg-[#FCF108]/30 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-[#665f00]">Aperçu</span><div className="flex items-start gap-4 border-b-2 border-[#2F2F2F] pb-6"><BrandLogo className="h-20 w-24 shrink-0"/><div><strong className="block text-lg">{company.name||'MADINA IMPORT'}</strong><p className="text-xs text-gray-400">{company.address}</p><p className="text-xs text-gray-400">Tél. : {company.contact} · WhatsApp : {company.whatsapp}</p><p className="text-xs text-gray-400">{company.email}</p><p className="mt-1 text-[10px] text-gray-400">NIF : {company.nif} · RCS : {company.rcs}</p><p className="text-[10px] text-gray-400">STAT : {company.stat}</p></div></div>{module==='devis'?<QuotePreview data={data}/>:module==='commandes'?<OrderPreview data={data} client={quickClient?data.new_client_name:labelFor('client_id')} contact={quickClient?data.new_client_contact:data.client_contact}/>:<InvoicePreview data={data} order={labelFor('order_id')} products={selectedOrderProducts}/>}</div></div><div className="flex flex-wrap justify-end gap-3 border-t border-gray-200 bg-white px-5 py-4"><button onClick={()=>setPreview(false)} className="btn-secondary">Retour et modifier</button><button onClick={persist} disabled={processing} className="btn-primary"><FileCheck2 size={17}/>{processing?'Enregistrement…':'Confirmer et enregistrer'}</button></div></div></div>}
 </AuthenticatedLayout>;
}

function MoneyInput({value,onChange,required=false,disabled=false}:{value:any;onChange:(value:string)=>void;required?:boolean;disabled?:boolean}){
 const digits=String(value??'').replace(/\D/g,'');
 return <input className="field disabled:cursor-not-allowed disabled:bg-gray-100 disabled:text-gray-400" type="text" inputMode="numeric" value={digits?new Intl.NumberFormat('de-DE').format(Number(digits)):''} onChange={event=>onChange(event.target.value.replace(/\D/g,''))} placeholder="0 Ar" required={required} disabled={disabled}/>;
}

function QuickClientFields({data,errors,setData,context}:{data:any;errors:Record<string,string>;setData:any;context:string}){
 return <div className="rounded-xl border border-[#FCF108] bg-[#FCF108]/5 p-4"><p className="mb-3 text-xs font-bold text-[#665f00]">Nouveau client — créé avec {context==='paiements'?'le paiement':'la commande'}</p><div className="grid gap-3 sm:grid-cols-2"><input className="field" placeholder="Nom du client *" value={data.new_client_name} onChange={event=>setData('new_client_name',event.target.value)} required/><input className="field" placeholder="Contact *" value={data.new_client_contact} onChange={event=>setData('new_client_contact',event.target.value)} required/><select className="field" value={data.new_client_type} onChange={event=>setData('new_client_type',event.target.value)}><option value="particulier">Particulier</option><option value="revendeur">Revendeur</option><option value="entrepreneur">Entrepreneur</option><option value="hotel">Hôtel</option></select><input className="field" placeholder="Adresse" value={data.new_client_address} onChange={event=>setData('new_client_address',event.target.value)}/></div>{['new_client_name','new_client_contact','new_client_type'].map(key=>errors[key]&&<p key={key} className="mt-1 text-xs text-[#BD2433]">{errors[key]}</p>)}</div>;
}

function PremiumStarRating({value,onChange}:{value:number;onChange:(value:number)=>void}){
 const [hovered,setHovered]=useState(0);
 const labels=['Non évaluée','Faible','Correcte','Bonne','Très bonne','Excellente'];
 const visible=hovered||value;
 return <div className="flex h-[43px] items-center justify-between gap-3 rounded-xl border border-gray-200 bg-gradient-to-r from-white to-[#FCF108]/5 px-3 shadow-sm" role="radiogroup" aria-label="Qualité du fournisseur"><div className="flex gap-0.5" onMouseLeave={()=>setHovered(0)}>{[1,2,3,4,5].map(star=><button key={star} type="button" role="radio" aria-checked={value===star} aria-label={`${star} étoile${star>1?'s':''} — ${labels[star]}`} onMouseEnter={()=>setHovered(star)} onFocus={()=>setHovered(star)} onBlur={()=>setHovered(0)} onClick={()=>onChange(star)} className="group rounded-md p-0.5 transition hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-[#BD2433]/30"><Star size={21} strokeWidth={1.8} className={`transition-all ${star<=visible?'fill-[#FCF108] text-[#D5C900] drop-shadow-sm':'fill-white text-gray-300 group-hover:text-[#D5C900]'}`}/></button>)}</div><span className="shrink-0 text-xs text-gray-400"><strong className="font-semibold text-gray-700">{labels[visible]}</strong> · {value||0}/5</span></div>;
}

function SupplierProductEditor({products,errors,onChange}:{products:any[];errors:Record<string,string>;onChange:(products:any[])=>void}){
 const add=()=>onChange([...products,{name:'',specifications:'',price:0,local_delivery:0,packaging:0,cbm:'',freight:0,margin:0,contact:'',source_url:'',photo:null}]);
 const update=(index:number,key:string,value:any)=>onChange(products.map((product,position)=>position===index?{...product,[key]:value}:product));
 return <div className="mt-8 border-t border-gray-100 pt-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-bold">Produits / articles du fournisseur</h2><p className="text-xs text-gray-400">Catalogue, prix et conditions proposés par ce fournisseur.</p></div><button type="button" onClick={add} className="btn-secondary"><Plus size={16}/>Ajouter un produit / article</button></div>
 {!products.length&&<button type="button" onClick={add} className="w-full rounded-xl border border-dashed border-gray-300 bg-gray-50 p-6 text-xs text-gray-400 hover:border-[#FCF108]">Aucun produit enregistré. Ajouter le premier article.</button>}
 <div className="space-y-4">{products.map((product,index)=><article key={index} className="rounded-2xl border border-gray-200 bg-[#FAFAF8] p-4"><div className="mb-4 flex items-center justify-between"><strong className="text-sm">Produit / article {index+1}</strong><button type="button" onClick={()=>onChange(products.filter((_,position)=>position!==index))} className="grid size-8 place-items-center rounded-lg text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
  <CatalogInput label="Nom du produit / article" required value={product.name} onChange={value=>update(index,'name',value)} error={errors[`products.${index}.name`]}/><CatalogInput label="Prix fournisseur (Ar)" type="number" value={product.price} onChange={value=>update(index,'price',value)} error={errors[`products.${index}.price`]}/><CatalogInput label="Contact de l’article" value={product.contact} onChange={value=>update(index,'contact',value)}/><CatalogInput label="Livraison Chine (Ar)" type="number" value={product.local_delivery} onChange={value=>update(index,'local_delivery',value)}/><CatalogInput label="Emballage (Ar)" type="number" value={product.packaging} onChange={value=>update(index,'packaging',value)}/><CatalogInput label="CBM estimé" type="number" step="0.0001" value={product.cbm} onChange={value=>update(index,'cbm',value)}/><CatalogInput label="Fret estimé (Ar)" type="number" value={product.freight} onChange={value=>update(index,'freight',value)}/><CatalogInput label="Marge indicative (Ar)" type="number" value={product.margin} onChange={value=>update(index,'margin',value)}/><CatalogInput label="Lien 1688 / Taobao" type="url" value={product.source_url} onChange={value=>update(index,'source_url',value)} error={errors[`products.${index}.source_url`]}/><div className="md:col-span-2"><label className="mb-1.5 block text-xs font-semibold text-gray-600">Spécifications</label><textarea className="field min-h-20" value={product.specifications||''} onChange={event=>update(index,'specifications',event.target.value)}/></div><div><label className="mb-1.5 block text-xs font-semibold text-gray-600">Photo optionnelle</label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>update(index,'photo',event.target.files?.[0]??null)} className="field file:mr-2 file:rounded-lg file:border-0 file:bg-[#FCF108] file:px-2 file:py-1.5 file:text-xs file:font-semibold"/>{product.photo_url&&<img src={product.photo_url} alt={product.name} className="mt-2 size-16 rounded-lg object-contain"/>}</div>
 </div></article>)}</div></div>;
}

function CatalogInput({label,value,onChange,error,type='text',step,required=false}:{label:string;value:any;onChange:(value:string)=>void;error?:string;type?:string;step?:string;required?:boolean}){
 return <div><label className="mb-1.5 block text-xs font-semibold text-gray-600">{label}{required&&<span className="ml-1 text-[#BD2433]">*</span>}</label><input className="field" type={type} min={type==='number'?0:undefined} step={step||(type==='number'?'0.01':undefined)} value={value??''} onChange={event=>onChange(event.target.value)} required={required}/>{error&&<p className="mt-1 text-xs text-[#BD2433]">{error}</p>}</div>;
}

function OrderProductGallery({products,context}:{products:any[];context:string}){
 return <div className="mt-8 border-t border-gray-100 pt-6"><div className="mb-4"><h2 className="text-base font-bold">Articles réels de la commande</h2><p className="text-xs text-gray-400">Ces photos proviennent de la commande et seront utilisées dans la {context}.</p></div>{products.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{products.map((product,index)=><div key={index} className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="grid h-32 place-items-center bg-[#F8F8F6]">{product.photo_url?<img src={product.photo_url} alt={product.name} className="size-full object-cover"/>:<span className="px-3 text-center text-xs text-gray-400">Photo réelle non ajoutée dans la commande</span>}</div><div className="p-3"><strong className="block text-sm">{product.name}</strong><span className="block text-xs text-gray-400">Quantité : {product.quantity}</span><span className="text-xs font-semibold text-gray-600">Prix unitaire : {money(product.unit_price)}</span></div></div>)}</div>:<div className="rounded-xl border border-dashed border-gray-300 p-5 text-center text-xs text-gray-400">Sélectionnez une commande pour afficher ses articles et leurs photos réelles.</div>}</div>;
}

function PackageEditor({packages,items,errors,onChange}:{packages:any[];items:any[];errors:Record<string,string>;onChange:(packages:any[])=>void}){
 const addPackage=()=>onChange([...packages,{reference:`COLIS-${packages.length+1}`,billing_unit:'kg',weight_kg:'',volume_cbm:'',notes:'',items:[{item_index:0,quantity:1}]}]);
 const updatePackage=(index:number,key:string,value:any)=>onChange(packages.map((pack,packIndex)=>packIndex===index?{...pack,[key]:value}:pack));
 const removePackage=(index:number)=>onChange(packages.filter((_,packIndex)=>packIndex!==index));
 const addLine=(index:number)=>updatePackage(index,'items',[...(packages[index].items||[]),{item_index:0,quantity:1}]);
 const updateLine=(packageIndex:number,lineIndex:number,key:string,value:any)=>updatePackage(packageIndex,'items',(packages[packageIndex].items||[]).map((line:any,index:number)=>index===lineIndex?{...line,[key]:value}:line));
 const removeLine=(packageIndex:number,lineIndex:number)=>{const lines=packages[packageIndex].items||[];if(lines.length>1)updatePackage(packageIndex,'items',lines.filter((_:any,index:number)=>index!==lineIndex));};
 const totalKg=packages.reduce((sum,pack)=>sum+Number(pack.weight_kg||0),0),totalCbm=packages.reduce((sum,pack)=>sum+Number(pack.volume_cbm||0),0);
 return <div className="mt-8 border-t border-gray-100 pt-6">
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-bold">Colis de la commande</h2><p className="text-xs text-gray-400">Un colis peut contenir plusieurs produits. Mesurez-le en kilogrammes ou en CBM.</p></div><button type="button" onClick={addPackage} className="btn-secondary"><Plus size={16}/>Ajouter un colis</button></div>
  {!packages.length&&<div className="rounded-xl border border-dashed border-gray-300 bg-gray-50 p-5 text-center text-xs text-gray-400">Aucun colis défini. Vous pouvez enregistrer la commande et compléter les colis plus tard.</div>}
  <div className="space-y-4">{packages.map((pack,packageIndex)=><div key={packageIndex} className="rounded-xl border border-[#FCF108]/70 bg-[#FCF108]/5 p-4">
   <div className="mb-4 flex items-center justify-between"><strong className="text-sm">Colis {packageIndex+1}</strong><button type="button" onClick={()=>removePackage(packageIndex)} className="grid size-8 place-items-center rounded-lg text-gray-400 hover:bg-red-50 hover:text-red-600" title="Retirer le colis"><Trash2 size={15}/></button></div>
   <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div><label className="mb-1.5 block text-xs font-semibold text-gray-600">Référence *</label><input className="field" value={pack.reference||''} onChange={event=>updatePackage(packageIndex,'reference',event.target.value)} required/></div><div><label className="mb-1.5 block text-xs font-semibold text-gray-600">Mesure facturée *</label><select className="field" value={pack.billing_unit||'kg'} onChange={event=>updatePackage(packageIndex,'billing_unit',event.target.value)}><option value="kg">Poids (kg)</option><option value="cbm">Volume (CBM)</option></select></div><div><label className="mb-1.5 block text-xs font-semibold text-gray-600">Poids réel (kg){pack.billing_unit==='kg'&&' *'}</label><input className="field" type="number" min="0" step="0.001" value={pack.weight_kg??''} onChange={event=>updatePackage(packageIndex,'weight_kg',event.target.value)} required={pack.billing_unit==='kg'}/></div><div><label className="mb-1.5 block text-xs font-semibold text-gray-600">Volume réel (CBM){pack.billing_unit==='cbm'&&' *'}</label><input className="field" type="number" min="0" step="0.0001" value={pack.volume_cbm??''} onChange={event=>updatePackage(packageIndex,'volume_cbm',event.target.value)} required={pack.billing_unit==='cbm'}/></div></div>
   {(errors[`packages.${packageIndex}.reference`]||errors[`packages.${packageIndex}.weight_kg`]||errors[`packages.${packageIndex}.volume_cbm`])&&<p className="mt-2 text-xs text-[#BD2433]">{errors[`packages.${packageIndex}.reference`]||errors[`packages.${packageIndex}.weight_kg`]||errors[`packages.${packageIndex}.volume_cbm`]}</p>}
   <div className="mt-4 rounded-xl bg-white p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-gray-500">Contenu du colis</span><button type="button" onClick={()=>addLine(packageIndex)} className="text-xs font-semibold text-[#BD2433]">+ Ajouter un article</button></div><div className="space-y-2">{(pack.items||[]).map((line:any,lineIndex:number)=><div key={lineIndex} className="grid items-end gap-2 sm:grid-cols-[1fr_130px_36px]"><div><label className="mb-1 block text-[10px] font-semibold text-gray-500">Produit / article</label><select className="field" value={line.item_index??0} onChange={event=>updateLine(packageIndex,lineIndex,'item_index',Number(event.target.value))} required>{items.map((item,index)=><option key={index} value={index}>{item.name||`Produit ${index+1}`}</option>)}</select></div><div><label className="mb-1 block text-[10px] font-semibold text-gray-500">Quantité dans ce colis</label><input className="field" type="number" min="0.001" step="0.001" value={line.quantity??1} onChange={event=>updateLine(packageIndex,lineIndex,'quantity',event.target.value)} required/></div><button type="button" onClick={()=>removeLine(packageIndex,lineIndex)} disabled={(pack.items||[]).length===1} className="grid size-9 place-items-center rounded-lg text-gray-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-30"><Trash2 size={14}/></button>{errors[`packages.${packageIndex}.items.${lineIndex}.quantity`]&&<p className="text-xs text-[#BD2433] sm:col-span-3">{errors[`packages.${packageIndex}.items.${lineIndex}.quantity`]}</p>}</div>)}</div></div>
   <div className="mt-3"><label className="mb-1 block text-[10px] font-semibold text-gray-500">Note sur le colis</label><input className="field" value={pack.notes||''} onChange={event=>updatePackage(packageIndex,'notes',event.target.value)} placeholder="Carton renforcé, fragile…"/></div>
  </div>)}</div>
  {!!packages.length&&<div className="ml-auto mt-4 grid max-w-sm grid-cols-2 gap-3 rounded-xl bg-[#2F2F2F] p-4 text-white"><div><span className="block text-[10px] text-white/50">Poids total</span><strong>{totalKg.toLocaleString('fr-FR')} kg</strong></div><div><span className="block text-[10px] text-white/50">Volume total</span><strong>{totalCbm.toLocaleString('fr-FR')} CBM</strong></div></div>}
 </div>;
}

function OrderPreview({data,client,contact}:{data:any;client:string;contact?:string}){
 const items=data.items||[],packages=data.packages||[];
 const total=items.reduce((sum:number,item:any)=>sum+Number(item.client_total||0),0),deposit=Number(data.deposit||0);
 return <div className="pt-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Bon de commande</p><h2 className="mt-1 text-2xl font-black">COMMANDE</h2><p className="mt-1 text-xs text-gray-400">Numéro attribué après sauvegarde</p></div><dl className="text-right text-xs"><dt className="text-gray-400">Date de commande</dt><dd className="font-semibold">{data.ordered_at?new Date(data.ordered_at).toLocaleDateString('fr-FR'):'—'}</dd><dt className="mt-2 text-gray-400">Mode d’envoi</dt><dd className="font-semibold capitalize">{String(data.shipping_mode||'Non défini')}</dd></dl></div>
 <div className="mt-7 rounded-xl bg-[#F8F8F6] p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Client</p><strong className="mt-1 block">{client}</strong>{contact&&<span className="mt-1 block text-xs text-gray-500">{contact}</span>}</div>
 <div className="mt-7 grid gap-4 sm:grid-cols-2">{items.map((item:any,index:number)=><article key={index} className="overflow-hidden rounded-xl border border-gray-200"><ProductPhoto item={item}/><div className="p-4"><div className="flex items-start justify-between gap-3"><strong>{item.name||`Produit ${index+1}`}</strong><span className="rounded bg-gray-100 px-2 py-1 text-xs font-bold">Qté {item.quantity||0}</span></div><p className="mt-2 text-xs text-gray-400">{item.specifications||'Aucune spécification'}</p><div className="mt-3 space-y-2 border-t border-gray-100 pt-3 text-sm"><Line label="Prix unitaire" value={money(Number(item.quantity)>0?Number(item.client_total)/Number(item.quantity):0)}/><Line label="Total" value={money(item.client_total)}/></div></div></article>)}</div>
 {!!packages.length&&<div className="mt-7"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Colis prévus</p><div className="mt-3 space-y-3">{packages.map((pack:any,index:number)=><div key={index} className="rounded-xl border border-gray-200 p-4"><div className="flex flex-wrap justify-between gap-3"><strong>{pack.reference||`Colis ${index+1}`}</strong><span className="text-xs text-gray-500">{pack.weight_kg?`${pack.weight_kg} kg`:''}{pack.weight_kg&&pack.volume_cbm?' · ':''}{pack.volume_cbm?`${pack.volume_cbm} CBM`:''}</span></div><div className="mt-2 flex flex-wrap gap-2">{(pack.items||[]).map((line:any,lineIndex:number)=><span key={lineIndex} className="rounded-lg bg-[#FCF108]/20 px-2.5 py-1 text-xs">{items[Number(line.item_index)]?.name||`Produit ${Number(line.item_index)+1}`} × {line.quantity}</span>)}</div></div>)}</div></div>}
 <div className="ml-auto mt-8 max-w-sm space-y-3 text-sm"><Line label="Total commande" value={money(total)}/><Line label="Acompte" value={money(deposit)}/><div className="flex justify-between border-t-2 border-[#2F2F2F] pt-3 text-lg font-black"><span>Reste à payer</span><span>{money(Math.max(0,total-deposit))}</span></div></div><p className="mt-8 text-xs text-gray-400">Statut prévu : <strong className="capitalize text-gray-600">{String(data.status||'brouillon').replaceAll('_',' ')}</strong></p></div>;
}

function ProductPhoto({item}:{item:any}){
 const [source,setSource]=useState<string|null>(item.photo_url||null);
 useEffect(()=>{if(!(item.photo instanceof File)){setSource(item.photo_url||null);return;}const url=URL.createObjectURL(item.photo);setSource(url);return()=>URL.revokeObjectURL(url);},[item.photo,item.photo_url]);
 return source?<div className="grid h-44 place-items-center bg-[#F5F5F2]"><img src={source} alt={item.name||'Produit'} className="size-full object-contain"/></div>:null;
}

function QuotePreview({data}:{data:any}){
 const items=data.items||[]; const total=items.reduce((sum:number,item:any)=>sum+Number(item.total||0),0);
 return <div className="pt-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Devis client</p><h2 className="mt-1 text-2xl font-black">DEVIS</h2><p className="mt-1 text-xs text-gray-400">Numéro attribué après sauvegarde</p></div><dl className="text-right text-xs"><dt className="text-gray-400">Date</dt><dd className="font-semibold">{data.quote_date?new Date(`${data.quote_date}T00:00:00`).toLocaleDateString('fr-FR'):'—'}</dd><dt className="mt-2 text-gray-400">Valide jusqu’au</dt><dd className="font-semibold">{data.valid_until?new Date(data.valid_until).toLocaleDateString('fr-FR'):'—'}</dd><dt className="mt-2 text-gray-400">Mode d’envoi</dt><dd className="font-semibold capitalize">{data.shipping_mode||'—'}</dd></dl></div><div className="mt-7 rounded-xl bg-[#F8F8F6] p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Destinataire</p><strong className="mt-1 block">{data.client_name||'—'}</strong><span className="text-xs text-gray-500">{data.client_contact}</span></div><div className="mt-7 space-y-3">{items.map((item:any,index:number)=><div key={index} className="grid items-center gap-4 rounded-xl border border-gray-200 p-3 sm:grid-cols-[96px_1fr_auto_auto_auto]"><div className="w-24 shrink-0"><ProductPhoto item={item}/></div><div className="min-w-0"><strong>{item.name||'—'}</strong>{item.specifications&&<p className="text-xs text-gray-400">{item.specifications}</p>}</div><span className="text-xs">Qté {item.quantity||0}</span><span className="text-right text-xs text-gray-500"><small className="block">Prix unitaire</small><strong className="text-gray-700">{money(Number(item.quantity)>0?Number(item.total)/Number(item.quantity):0)}</strong></span><strong>{money(item.total)}</strong></div>)}</div><div className="ml-auto mt-7 max-w-sm"><div className="flex justify-between border-t-2 border-[#2F2F2F] pt-3 text-lg font-black"><span>Total proposé</span><span>{money(total)}</span></div></div><div className="mt-8 grid gap-3 text-xs sm:grid-cols-2">{data.shipping_delay&&<Remark label="Délai d’expédition" value={data.shipping_delay}/>} {data.payment_terms&&<Remark label="Conditions de paiement" value={data.payment_terms}/>} {data.bank_details&&<Remark label="Informations bancaires" value={data.bank_details}/>} {data.warranty&&<Remark label="Garantie" value={data.warranty}/>} {data.notes&&<Remark label="Note / remarque" value={data.notes}/>}</div><p className="mt-8 text-xs text-gray-400">Statut prévu : <strong className="capitalize text-gray-600">{String(data.status||'brouillon').replaceAll('_',' ')}</strong></p></div>;
}

function Remark({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#F8F8F6] p-3"><strong className="block text-[10px] uppercase tracking-wide text-gray-400">{label}</strong><span className="mt-1 block whitespace-pre-wrap">{value}</span></div>}

function InvoicePreview({data,order,products}:{data:any;order:string;products:any[]}){
 const subtotal=Number(data.subtotal||0),paid=Number(data.paid_amount||0);
 return <div className="pt-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{data.type==='frais'?'Facture de frais':'Facture produits'}</p><h2 className="mt-1 text-2xl font-black">FACTURE</h2><p className="mt-1 text-xs text-gray-400">Numéro attribué après sauvegarde</p></div><dl className="text-right text-xs"><dt className="text-gray-400">Date d’émission</dt><dd className="font-semibold">{data.issued_at?new Date(data.issued_at).toLocaleDateString('fr-FR'):'—'}</dd><dt className="mt-2 text-gray-400">Commande</dt><dd className="font-semibold">{order}</dd></dl></div><div className="mt-8 rounded-xl border border-gray-200 p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Désignation</p><div className="mt-3 flex justify-between gap-4"><strong>{data.type==='frais'?'Frais liés à la commande':'Produits commandés'}</strong><strong>{money(subtotal)}</strong></div></div>{data.type==='produits'&&products.length>0&&<div className="mt-5 grid grid-cols-2 gap-3">{products.map((product,index)=><div key={index} className="flex items-center gap-3 rounded-xl border border-gray-200 p-2">{product.photo_url?<img src={product.photo_url} alt={product.name} className="size-14 rounded-lg object-cover"/>:<span className="grid size-14 shrink-0 place-items-center rounded-lg bg-gray-100 text-[9px] text-gray-400">Sans photo</span>}<div><strong className="block text-xs">{product.name}</strong><span className="block text-[10px] text-gray-400">Qté : {product.quantity}</span><span className="text-[10px] font-semibold text-gray-600">Prix unitaire : {money(product.unit_price)}</span></div></div>)}</div>}<div className="ml-auto mt-8 max-w-sm space-y-3 text-sm"><Line label="Total facturé" value={money(subtotal)}/><Line label="Montant reçu" value={money(paid)}/><div className="flex justify-between border-t-2 border-[#2F2F2F] pt-3 text-lg font-black"><span>Reste à payer</span><span>{money(Math.max(0,subtotal-paid))}</span></div></div><p className="mt-10 text-xs text-gray-400">Statut prévu : <strong className="capitalize text-gray-600">{String(data.status||'brouillon').replaceAll('_',' ')}</strong></p></div>;
}

function Line({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-5"><span className="text-gray-500">{label}</span><strong>{value}</strong></div>}
