import BrandLogo from '@/Components/BrandLogo';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Box, CalendarDays, FilePlus2, PackageCheck, Pencil, Printer, Ship, UserRound } from 'lucide-react';

const money=(value:any)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(Number(value||0))+' Ar';
const number=(value:any,maximumFractionDigits=3)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits}).format(Number(value||0));
const date=(value:any)=>value?new Date(value).toLocaleDateString('fr-FR'):'—';
const label=(value:any)=>String(value||'—').replaceAll('_',' ');

export default function OrderShow({order,items,packages}:{order:any;items:any[];packages:any[]}){
 const totalWeight=packages.reduce((sum,item)=>sum+Number(item.weight_kg||0),0);
 const totalCbm=packages.reduce((sum,item)=>sum+Number(item.volume_cbm||0),0);
 return <AuthenticatedLayout
  header={<><Link href="/modules/commandes" className="mb-3 inline-flex items-center gap-2 text-xs font-semibold text-gray-400 hover:text-[#BD2433]"><ArrowLeft size={14}/>Retour aux commandes</Link><p className="eyebrow">Aperçu de la commande</p><h1 className="page-title">{order.number}</h1><p className="mt-1 text-sm text-gray-400">Produits réels, photos, colis et informations financières.</p></>}
  action={<div className="flex flex-wrap gap-2 print:hidden"><button type="button" onClick={()=>window.print()} className="btn-secondary"><Printer size={16}/>Imprimer</button><Link href={`/modules/factures/create?order_id=${order.id}`} className="btn-secondary"><FilePlus2 size={16}/>Créer une facture</Link><Link href={`/modules/commandes/${order.id}/edit`} className="btn-primary"><Pencil size={16}/>Modifier</Link></div>}
 >
  <Head title={`Commande ${order.number}`}/>
  <div className="mx-auto max-w-6xl space-y-5">
   <section className="panel overflow-hidden !p-0">
    <div className="flex flex-wrap items-start justify-between gap-5 bg-[#2F2F2F] p-6 text-white md:p-8"><div className="flex items-center gap-4"><BrandLogo className="h-20 w-24 shrink-0"/><div><p className="text-xs uppercase tracking-[.2em] text-white/45">Bon de commande</p><h2 className="mt-1 text-2xl font-black">{order.number}</h2><span className="mt-2 inline-flex rounded-full bg-[#FCF108] px-3 py-1 text-xs font-bold capitalize text-[#2F2F2F]">{label(order.status)}</span></div></div><div className="grid gap-2 text-sm text-white/70"><span className="flex items-center gap-2"><CalendarDays size={15}/>Commande du {date(order.ordered_at)}</span><span className="flex items-center gap-2"><Ship size={15}/>{order.shipping_mode?`Envoi ${label(order.shipping_mode)}`:'Mode d’envoi non défini'}</span><span className="flex items-center gap-2"><UserRound size={15}/>Manager : {order.manager_name}</span></div></div>
    <div className="grid gap-5 p-6 md:grid-cols-2 md:p-8"><div className="rounded-xl bg-[#F8F8F6] p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Client</p><strong className="mt-2 block text-lg">{order.client_name}</strong><p className="mt-1 text-sm text-gray-500">{order.client_contact||'Contact non renseigné'}</p><p className="text-sm text-gray-500">{order.client_address||'Adresse non renseignée'}</p></div><div className="grid grid-cols-2 gap-3"><Summary label="Total client" value={money(order.client_total)}/><Summary label="Acompte reçu" value={money(order.deposit)}/><Summary label="Reste à payer" value={money(order.balance_due)} accent/><Summary label="Nombre d’articles" value={String(items.length)}/></div></div>
   </section>

   <section className="panel"><div className="panel-head"><div><h2>Produits / articles de la commande</h2><p>Photos réelles et informations enregistrées</p></div><span className="grid size-9 place-items-center rounded-xl bg-[#FCF108]/20 text-[#817900]"><PackageCheck size={19}/></span></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border border-gray-200 bg-white">{item.photo_url&&<div className="grid h-52 place-items-center bg-[#F5F5F2]"><img src={item.photo_url} alt={item.name} className="size-full object-contain"/></div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><strong className="text-base">{item.name}</strong><span className="rounded-lg bg-gray-100 px-2 py-1 text-xs font-bold">Qté {number(item.quantity)}</span></div>{item.specifications&&<p className="mt-2 text-sm leading-relaxed text-gray-500">{item.specifications}</p>}<dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 border-t border-gray-100 pt-3 text-xs"><Info label="Fournisseur" value={item.supplier_name||'—'}/><Info label="Prix client" value={money(item.client_total)}/><Info label="Poids" value={item.weight?`${number(item.weight)} kg`:'—'}/><Info label="Volume" value={item.cbm?`${number(item.cbm,4)} CBM`:'—'}/></dl>{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-semibold text-[#BD2433] hover:underline">Voir la source du produit</a>}</div></article>)}</div>
   </section>

   <section className="panel"><div className="panel-head"><div><h2>Colis assemblés</h2><p>Répartition des articles et mesures réelles</p></div><span className="grid size-9 place-items-center rounded-xl bg-gray-100 text-gray-600"><Box size={19}/></span></div>
    {packages.length?<><div className="mt-5 grid gap-4 lg:grid-cols-2">{packages.map(pack=><article key={pack.id} className="rounded-2xl border border-gray-200 p-5"><div className="flex items-start justify-between gap-4"><div><strong>{pack.reference}</strong><p className="mt-1 text-xs text-gray-400">Facturation par {pack.billing_unit==='kg'?'poids':'volume'}</p></div><span className="rounded-lg bg-[#FCF108]/25 px-3 py-1 text-xs font-bold uppercase">{pack.billing_unit}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><Summary label="Poids réel" value={pack.weight_kg?`${number(pack.weight_kg)} kg`:'—'}/><Summary label="Volume réel" value={pack.volume_cbm?`${number(pack.volume_cbm,4)} CBM`:'—'}/></div><div className="mt-4 border-t border-gray-100 pt-3"><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-gray-400">Contenu</p>{pack.items.map((item:any,index:number)=><div key={index} className="flex justify-between gap-4 py-1.5 text-sm"><span>{item.name}</span><strong>Qté {number(item.quantity)}</strong></div>)}</div>{pack.notes&&<p className="mt-3 rounded-lg bg-gray-50 p-3 text-xs text-gray-500">{pack.notes}</p>}</article>)}</div><div className="ml-auto mt-5 grid max-w-md grid-cols-2 gap-3 rounded-xl bg-[#2F2F2F] p-4 text-white"><Summary label="Poids total" value={`${number(totalWeight)} kg`} dark/><Summary label="Volume total" value={`${number(totalCbm,4)} CBM`} dark/></div></>:<div className="mt-5 rounded-xl border border-dashed border-gray-300 p-8 text-center text-sm text-gray-400">Aucun colis n’a encore été défini pour cette commande.</div>}
   </section>
   {order.notes&&<section className="panel"><h2 className="text-sm font-bold">Notes internes</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-gray-500">{order.notes}</p></section>}
  </div>
 </AuthenticatedLayout>;
}

function Summary({label,value,accent=false,dark=false}:{label:string;value:string;accent?:boolean;dark?:boolean}){return <div className={`rounded-xl p-3 ${dark?'bg-white/5':accent?'bg-red-50':'bg-[#F8F8F6]'}`}><span className={`block text-[10px] ${dark?'text-white/45':'text-gray-400'}`}>{label}</span><strong className={`mt-1 block text-sm ${accent?'text-[#BD2433]':''}`}>{value}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-gray-400">{label}</dt><dd className="mt-0.5 font-semibold text-gray-700">{value}</dd></div>}
