import PremiumDatePicker from '@/Components/PremiumDatePicker';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Eraser, FileDown, Save } from 'lucide-react';
import { FormEvent, PointerEvent, useEffect, useRef, useState } from 'react';

type Item={order_item_id:number;name:string;ordered_quantity:number;remaining_quantity?:number;delivered_quantity?:number};
type Order={id:number;number:string;status:string;client_name:string;client_contact?:string;client_address?:string;items:Item[]};

export default function Form({orders,selectedOrderId,note,statuses}:{orders:Order[];selectedOrderId?:number|null;note?:any;statuses:{value:string;label:string}[]}){
 const initialOrder=orders.find(order=>order.id===Number(note?.order_id||selectedOrderId));
 const currentQuantities=new Map<number,number>((note?.items||[]).map((item:Item)=>[Number(item.order_item_id),Number(item.delivered_quantity||0)]));
 const initialItems=initialOrder?.items.map(item=>({...item,delivered_quantity:currentQuantities.get(Number(item.order_item_id))??item.remaining_quantity}))||[];
 const {data,setData,post,processing,errors}=useForm<any>({order_id:note?.order_id||selectedOrderId||'',delivered_at:note?.delivered_at||new Date().toISOString().slice(0,10),delivery_address:note?.delivery_address||initialOrder?.client_address||'',package_count:note?.package_count||1,observations:note?.observations||'',receiver_name:note?.receiver_name||'',order_status:note?.status||'a_livrer',items:initialItems,signature_data:'',proof:null,...(note?{_method:'put'}:{})});
 const selected=orders.find(order=>order.id===Number(data.order_id));
 const chooseOrder=(value:string)=>{const order=orders.find(item=>item.id===Number(value));setData((current:any)=>({...current,order_id:value,delivery_address:order?.client_address||'',items:order?.items.map(item=>({...item,delivered_quantity:item.remaining_quantity}))||[]}));};
 const updateQuantity=(index:number,value:string)=>setData('items',data.items.map((item:Item,itemIndex:number)=>itemIndex===index?{...item,delivered_quantity:value}:item));
 const submit=(event:FormEvent)=>{event.preventDefault();post(note?`/modules/bons-livraison/${note.id}`:'/modules/bons-livraison',{forceFormData:true,preserveScroll:true});};
 return <AuthenticatedLayout header={<><Link href="/modules/bons-livraison" className="mb-3 inline-flex items-center gap-2 text-xs font-semibold text-gray-400"><ArrowLeft size={14}/>Retour aux BL</Link><p className="eyebrow">Livraison</p><h1 className="page-title">{note?`Modifier ${note.number}`:'Nouveau bon de livraison'}</h1></>} action={note&&<a href={`/modules/bons-livraison/${note.id}/pdf`} className="btn-secondary"><FileDown size={17}/>Télécharger le PDF</a>}>
  <Head title={note?note.number:'Nouveau BL'}/><form onSubmit={submit} className="space-y-6">
   {Object.keys(errors).length>0&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Corrigez les champs signalés avant d’enregistrer.</div>}
   <section className="panel"><div className="grid gap-5 md:grid-cols-2"><Field label="N° de commande" error={errors.order_id}><select className="field" value={data.order_id} onChange={event=>chooseOrder(event.target.value)} required disabled={!!note}><option value="">Sélectionner…</option>{orders.map(order=><option key={order.id} value={order.id}>{order.number} — {order.client_name}</option>)}</select></Field><Field label="Date de livraison" error={errors.delivered_at}><PremiumDatePicker value={data.delivered_at} onChange={value=>setData('delivered_at',value)} required/></Field>{selected&&<div className="md:col-span-2 rounded-xl bg-[#F8F8F6] p-4 text-sm"><strong>{selected.client_name}</strong><p className="text-gray-500">{selected.client_contact||'Contact non renseigné'}</p></div>}<Field label="Lieu de livraison" error={errors.delivery_address}><input className="field" value={data.delivery_address} onChange={event=>setData('delivery_address',event.target.value)} required/></Field><Field label="Quantité de colis" error={errors.package_count}><input className="field" type="number" min="1" value={data.package_count} onChange={event=>setData('package_count',event.target.value)} required/></Field><Field label="Statut de la commande" error={errors.order_status}><select className="field" value={data.order_status} onChange={event=>setData('order_status',event.target.value)} required>{statuses.map(status=><option key={status.value} value={status.value}>{status.label}</option>)}</select></Field><Field label="Nom du réceptionnaire" error={errors.receiver_name}><input className="field" value={data.receiver_name} onChange={event=>setData('receiver_name',event.target.value)}/></Field><div className="md:col-span-2"><Field label="Observations" error={errors.observations}><textarea className="field min-h-24" value={data.observations} onChange={event=>setData('observations',event.target.value)}/></Field></div></div></section>
   <section className="panel"><h2 className="text-base font-bold">Produits livrés</h2><p className="mt-1 text-xs text-gray-400">Les quantités sont limitées au reliquat de la commande.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px]"><thead><tr><th>Produit</th><th>Commandée</th><th>Restante</th><th>À livrer</th></tr></thead><tbody>{data.items.map((item:Item,index:number)=><tr key={item.order_item_id}><td className="font-semibold">{item.name}</td><td>{item.ordered_quantity}</td><td>{item.remaining_quantity??item.ordered_quantity}</td><td><input className="field max-w-36" type="number" min="0" max={item.remaining_quantity??item.ordered_quantity} step="0.001" value={item.delivered_quantity??0} onChange={event=>updateQuantity(index,event.target.value)}/>{errors[`items.${index}.delivered_quantity`]&&<p className="mt-1 text-xs text-red-600">{errors[`items.${index}.delivered_quantity`]}</p>}</td></tr>)}</tbody></table>{!data.items.length&&<p className="py-8 text-center text-sm text-gray-400">Sélectionnez une commande.</p>}</div></section>
   <section className="panel"><div className="grid gap-6 lg:grid-cols-2"><SignaturePad existingUrl={note?.signature_url} onChange={value=>setData('signature_data',value)}/><div><h2 className="text-base font-bold">Preuve de livraison</h2><p className="mt-1 text-xs text-gray-400">Photo ou PDF, 5 Mo maximum. Une signature ou une preuve est obligatoire.</p>{note?.proof_url&&<a className="mt-3 inline-block text-sm font-semibold text-[#BD2433]" href={note.proof_url} target="_blank">Voir la preuve actuelle</a>}<input className="field mt-4 file:mr-3 file:rounded-lg file:border-0 file:bg-[#FCF108] file:px-3 file:py-1.5" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>setData('proof',event.target.files?.[0]||null)}/>{errors.proof&&<p className="mt-1 text-xs text-red-600">{errors.proof}</p>}</div></div></section>
   <div className="flex justify-end gap-3"><Link href="/modules/bons-livraison" className="btn-secondary">Annuler</Link><button className="btn-primary" disabled={processing}><Save size={17}/>{processing?'Enregistrement…':'Enregistrer le BL'}</button></div>
  </form>
 </AuthenticatedLayout>;
}

function Field({label,error,children}:{label:string;error?:string;children:any}){return <div><label className="mb-2 block text-xs font-semibold text-gray-600">{label}</label>{children}{error&&<p className="mt-1 text-xs text-red-600">{error}</p>}</div>}

function SignaturePad({existingUrl,onChange}:{existingUrl?:string;onChange:(value:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null);const hasInk=useRef(false);const [drawing,setDrawing]=useState(false);const [signed,setSigned]=useState(false);
 useEffect(()=>{const context=canvas.current?.getContext('2d');if(context){context.lineWidth=2;context.lineCap='round';context.strokeStyle='#2F2F2F';}},[]);
 const point=(event:PointerEvent<HTMLCanvasElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)*(event.currentTarget.width/rect.width),y:(event.clientY-rect.top)*(event.currentTarget.height/rect.height)}};
 const start=(event:PointerEvent<HTMLCanvasElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);const p=point(event),ctx=event.currentTarget.getContext('2d');ctx?.beginPath();ctx?.moveTo(p.x,p.y);setDrawing(true);};
 const move=(event:PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const p=point(event),ctx=event.currentTarget.getContext('2d');ctx?.lineTo(p.x,p.y);ctx?.stroke();hasInk.current=true;setSigned(true);};
 const finish=()=>{setDrawing(false);if(hasInk.current&&canvas.current)onChange(canvas.current.toDataURL('image/png'));};
 const clear=()=>{const element=canvas.current;element?.getContext('2d')?.clearRect(0,0,element.width,element.height);hasInk.current=false;setSigned(false);onChange('');};
 return <div><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Signature du client</h2><p className="mt-1 text-xs text-gray-400">Signez directement dans le cadre.</p></div><button type="button" onClick={clear} className="btn-secondary !px-3"><Eraser size={15}/>Effacer</button></div>{existingUrl&&!signed&&<img src={existingUrl} alt="Signature actuelle" className="mt-3 h-24 max-w-full rounded-xl border border-gray-200 bg-white object-contain"/>}<canvas ref={canvas} width={700} height={220} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} className="mt-3 h-40 w-full touch-none rounded-xl border-2 border-dashed border-gray-300 bg-white"/>
 </div>;
}
