import PublicContactForm from '@/Components/PublicContactForm';
import PublicLayout, { PublicConfig } from '@/Layouts/PublicLayout';
import { Head, usePage } from '@inertiajs/react';
import { ArrowUpRight, MapPin, MessageCircle } from 'lucide-react';

export default function Contact({publicConfig}:{publicConfig:PublicConfig}){
 const {flash}=usePage().props as any; const whatsapp=`https://wa.me/${publicConfig.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent("Bonjour Madina Import, je souhaite parler de mon projet.")}`;
 return <PublicLayout config={publicConfig}><Head title="Contact"><meta name="description" content="Présentez votre projet d’importation à l’équipe Madina Import en Chine et à Madagascar."/></Head><section className="public-section"><div className="public-container grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="public-kicker">Un projet à faire avancer ?</p><h1 className="mt-5 text-5xl font-black tracking-[-.045em] sm:text-6xl">Parlons-en simplement.</h1><p className="mt-6 max-w-xl leading-8 text-[#5E5E5E]">Décrivez votre besoin et les contraintes déjà connues. Notre équipe vous recontactera pour clarifier la suite.</p><div className="mt-10 space-y-4 border-y border-black/10 py-7"><ContactLine label="Madagascar" value={publicConfig.madagascar_phone}/><ContactLine label="Chine" value={publicConfig.china_phone}/></div><a href={whatsapp} target="_blank" rel="noreferrer" className="public-button mt-7"><MessageCircle size={17}/>Nous contacter sur WhatsApp<ArrowUpRight size={16}/></a>{publicConfig.facebook_url&&<a href={publicConfig.facebook_url} target="_blank" rel="noreferrer" className="public-text-link mt-5">Retrouvez-nous sur Facebook <ArrowUpRight size={16}/></a>}<div className="mt-10 flex gap-3 text-sm text-[#5E5E5E]"><MapPin className="shrink-0 text-[#C8102E]"/><p>Présence opérationnelle en Chine et accompagnement des projets à Madagascar.</p></div></div><div className="border border-black/10 bg-white p-6 sm:p-9"><h2 className="text-2xl font-black">Démarrer une demande</h2><p className="mb-7 mt-2 text-sm text-[#5E5E5E]">Les champs nous aident à orienter votre demande dès le premier échange.</p><PublicContactForm flash={flash?.success}/></div></div></section></PublicLayout>;
}
function ContactLine({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-5"><span className="text-sm text-[#5E5E5E]">{label}</span><strong>{value}</strong></div>}
