import { CatalogProduct } from '@/Components/PublicProductCard';
import PublicLayout, { PublicConfig } from '@/Layouts/PublicLayout';
import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, ArrowUpRight, CheckCircle2, ImageOff } from 'lucide-react';
import { useState } from 'react';

type Product=CatalogProduct&{description?:string|null;gallery:string[]};
const money=(value:number)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(value)+' Ar';

export default function ProductPage({product,publicConfig}:{product:Product;publicConfig:PublicConfig}){
 const images=[product.image_url,...product.gallery].filter(Boolean) as string[]; const [image,setImage]=useState(images[0]||null);
 const message=encodeURIComponent(`Bonjour Madina Import, je souhaite des informations sur le produit ${product.reference} — ${product.name}.`); const whatsapp=`https://wa.me/${publicConfig.whatsapp.replace(/\D/g,'')}?text=${message}`;
 return <PublicLayout config={publicConfig}><Head title={product.name}><meta name="description" content={product.short_description||`Produit ${product.name} disponible chez Madina Import.`}/></Head><section className="public-section"><div className="public-container"><Link href="/catalogue" className="public-text-link"><ArrowLeft size={16}/>Retour au catalogue</Link><div className="mt-9 grid gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><div className="grid aspect-[4/3] place-items-center bg-[#F6F5F1]">{image?<img src={image} alt={product.name} className="size-full object-contain p-8"/>:<ImageOff size={40} className="text-black/20"/>}</div>{images.length>1&&<div className="mt-3 grid grid-cols-5 gap-3">{images.map((src,index)=><button key={src} onClick={()=>setImage(src)} className={`aspect-square border bg-[#F6F5F1] ${image===src?'border-[#C8102E]':'border-black/10'}`} aria-label={`Afficher la photo ${index+1}`}><img src={src} alt="" className="size-full object-contain p-2"/></button>)}</div>}</div><div className="lg:pt-6"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#FFE600] px-3 py-1 text-[10px] font-black uppercase tracking-wider">{product.availability}</span>{product.category&&<span className="rounded-full bg-[#F6F5F1] px-3 py-1 text-[10px] font-black uppercase tracking-wider">{product.category}</span>}</div><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-[#5E5E5E]">Réf. {product.reference}</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">{product.name}</h1>{product.short_description&&<p className="mt-5 text-lg leading-8 text-[#5E5E5E]">{product.short_description}</p>}<div className="mt-7 border-y border-black/10 py-6"><small className="block uppercase tracking-wider text-[#5E5E5E]">Prix de vente</small><strong className="mt-2 block text-3xl">{product.price!==null&&product.price!==undefined?money(product.price):'Sur demande'}</strong></div>{product.description&&<div className="mt-7 whitespace-pre-line text-sm leading-7 text-[#5E5E5E]">{product.description}</div>}<div className="mt-8 flex items-start gap-3 bg-[#F6F5F1] p-4 text-sm leading-6"><CheckCircle2 size={20} className="mt-0.5 shrink-0 text-emerald-600"/><span>La disponibilité est issue du stock Madina Import. Notre équipe confirme les conditions lors de votre demande.</span></div><a href={whatsapp} target="_blank" rel="noreferrer" className="public-button mt-7">Demander sur WhatsApp <ArrowUpRight size={17}/></a></div></div></div></section></PublicLayout>;
}
