import { Link, usePage } from '@inertiajs/react';
import BrandLogo from '@/Components/BrandLogo';
import { PropsWithChildren, ReactNode, useState } from 'react';
import { Bell, Boxes, ChartNoAxesCombined, ChevronDown, Factory, FileText, Gauge, Landmark, LogOut, Menu, PackageCheck, ReceiptText, Scale, Search, Settings, Ship, ShoppingCart, Store, Users, WalletCards, X, BadgeDollarSign } from 'lucide-react';

const nav = [
 ['Dashboard','/dashboard',Gauge],['Clients','/modules/clients',Users],['Devis','/modules/devis',FileText],['Commandes','/modules/commandes',PackageCheck],['Paiements clients','/modules/paiements',WalletCards],['Factures','/modules/factures',ReceiptText],['Fournisseurs','/modules/fournisseurs',Factory],['Achats fournisseurs','/modules/achats',ShoppingCart],['Logistique','/modules/logistique',Ship],['Stock','/modules/stock',Boxes],['Ventes locales','/modules/ventes',Store],['Dépenses','/modules/depenses',Landmark],['Salaires et IRSA','/modules/salaires',BadgeDollarSign],['Fiscalité','/modules/fiscalite',Scale],['Rapports','/modules/rapports',ChartNoAxesCombined],['Paramètres','/modules/parametres',Settings],
] as const;

export default function Authenticated({ header, children, action }: PropsWithChildren<{header?:ReactNode; action?:ReactNode}>) {
 const [open,setOpen]=useState(false); const {auth}=usePage().props as any; const path=window.location.pathname;
 return <div className="min-h-screen bg-[#F8F8F6] text-[#2F2F2F]">
  {open&&<button aria-label="Fermer" className="fixed inset-0 z-30 bg-black/30 lg:hidden" onClick={()=>setOpen(false)}/>} 
  <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col bg-[#2F2F2F] text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex h-[96px] items-center justify-between border-b border-white/10 px-5"><Link href="/dashboard" className="flex items-center gap-2"><BrandLogo className="h-[72px] w-[86px] shrink-0"/><span><strong className="block text-[14px] tracking-wide text-[#FCF108]">MADINA IMPORT</strong><small className="text-[10px] text-white/55">Gestion & importation</small></span></Link><button onClick={()=>setOpen(false)} className="lg:hidden"><X size={20}/></button></div>
   <nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">{nav.map(([label,href,Icon])=>{const active=path===href;return <Link key={href} href={href} onClick={()=>setOpen(false)} className={`group flex items-center gap-3 rounded-[10px] px-3 py-2.5 text-[13px] font-medium transition ${active?'bg-[#FCF108] text-[#2F2F2F] shadow-sm':'text-white/70 hover:bg-white/10 hover:text-white'}`}><Icon size={17}/><span>{label}</span>{active&&<span className="ml-auto size-1.5 rounded-full bg-[#BD2433]"/>}</Link>})}</nav>
   <div className="space-y-2 border-t border-white/10 p-4"><div className="rounded-xl bg-white/5 p-3 text-xs text-white/55"><span className="mb-1 block font-semibold text-white/80">{auth?.user?.name||'Manager'}</span>Espace sécurisé · synchronisé à l’instant</div><Link href="/logout" method="post" as="button" className="flex w-full items-center gap-3 rounded-[10px] px-3 py-2.5 text-left text-[13px] font-semibold text-white/70 transition hover:bg-[#BD2433] hover:text-white"><LogOut size={17}/><span>Déconnexion</span></Link></div>
  </aside>
  <div className="lg:pl-[260px]"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-4 border-b border-[#E8E7E2] bg-white/95 px-4 backdrop-blur md:px-7"><button onClick={()=>setOpen(true)} className="rounded-lg p-2 hover:bg-gray-100 lg:hidden"><Menu size={21}/></button><form action="/modules/commandes" method="get" className="relative hidden max-w-sm flex-1 md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={17}/><input name="q" className="w-full rounded-xl border-0 bg-[#F5F5F2] py-2.5 pl-10 pr-3 text-sm focus:ring-2 focus:ring-[#BD2433]/20" placeholder="Rechercher une commande…"/></form><div className="ml-auto flex items-center gap-3"><Link href="/modules/rapports" aria-label="Notifications" className="relative rounded-xl border border-gray-200 p-2.5 text-gray-500"><Bell size={18}/><i className="absolute right-2 top-2 size-1.5 rounded-full bg-[#BD2433]"/></Link><Link href="/profile" className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-gray-50"><span className="grid size-9 place-items-center rounded-xl bg-[#BD2433] text-sm font-bold text-white">{auth?.user?.name?.slice(0,2).toUpperCase()||'MI'}</span><span className="hidden text-left sm:block"><strong className="block text-xs">{auth?.user?.name||'Manager'}</strong><small className="text-[10px] text-gray-400">Administrateur</small></span><ChevronDown size={14} className="text-gray-400"/></Link></div></header><main className="p-4 md:p-7"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div>{header}</div>{action}</div>{children}</main></div>
 </div>
}
