import { Link, usePage } from '@inertiajs/react';
import BrandLogo from '@/Components/BrandLogo';
import { PropsWithChildren, ReactNode, useState } from 'react';
import { Bell, BookOpen, Boxes, ChartNoAxesCombined, ChevronDown, ClipboardList, Factory, FileText, Gauge, Landmark, LogOut, Menu, PackageCheck, ReceiptText, Scale, Search, Settings, Ship, ShoppingCart, Store, UserCog, UserRound, Users, WalletCards, X, BadgeDollarSign } from 'lucide-react';

const nav = [
 ['Demandes publiques','/modules/demandes',ClipboardList],
 ['Dashboard','/dashboard',Gauge],['Clients','/modules/clients',Users],['Demandes de devis','/modules/demandes-devis',ClipboardList],['Devis','/modules/devis',FileText],['Commandes','/modules/commandes',PackageCheck],['Paiements clients','/modules/paiements',WalletCards],['Factures','/modules/factures',ReceiptText],['Fournisseurs','/modules/fournisseurs',Factory],['Achats fournisseurs','/modules/achats',ShoppingCart],['Logistique','/modules/logistique',Ship],['Stock','/modules/stock',Boxes],['Catalogue','/modules/catalogue',BookOpen],['Ventes locales','/modules/ventes',Store],['Dépenses','/modules/depenses',Landmark],['Employés','/modules/employes',UserRound],['Salaires et IRSA','/modules/salaires',BadgeDollarSign],['Fiscalité','/modules/fiscalite',Scale],['Rapports','/modules/rapports',ChartNoAxesCombined],['Paramètres','/modules/parametres',Settings],
] as const;

export default function Authenticated({ header, children, action }: PropsWithChildren<{header?:ReactNode; action?:ReactNode}>) {
 const [open,setOpen]=useState(false); const {auth}=usePage().props as any; const path=window.location.pathname;
 const superAdmin=auth?.user?.role==='super_admin';
 const allowed=(href:string)=>superAdmin||auth?.user?.permissions?.includes(href==='/dashboard'?'dashboard':href.replace('/modules/',''));
 const visibleNav=nav.filter(([,href])=>allowed(href));
 const roleLabel=superAdmin?'Super administrateur':auth?.user?.role==='assistant'?'Assistant':'Utilisateur';
 return <div className="min-h-screen bg-[#F8F8F6] text-[#2F2F2F]">
  {open&&<button aria-label="Fermer" className="fixed inset-0 z-30 bg-black/30 lg:hidden" onClick={()=>setOpen(false)}/>} 
  <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col bg-[#2F2F2F] text-white transition-transform print:hidden lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex h-[96px] items-center justify-between border-b border-white/10 px-5"><Link href="/dashboard" className="flex items-center gap-2"><BrandLogo className="h-[72px] w-[86px] shrink-0"/><span><strong className="block text-[14px] tracking-wide text-[#FCF108]">MADINA IMPORT</strong><small className="text-[10px] text-white/55">Gestion & importation</small></span></Link><button onClick={()=>setOpen(false)} className="lg:hidden"><X size={20}/></button></div>
   <nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">{visibleNav.map(([label,href,Icon])=>{const active=path===href||path.startsWith(`${href}/`);return <Link key={href} href={href} onClick={()=>setOpen(false)} className={`group flex items-center gap-3 rounded-[10px] px-3 py-2.5 text-[13px] font-medium transition ${active?'bg-[#FCF108] text-[#2F2F2F] shadow-sm':'text-white/70 hover:bg-white/10 hover:text-white'}`}><Icon size={17}/><span>{label}</span>{active&&<span className="ml-auto size-1.5 rounded-full bg-[#BD2433]"/>}</Link>})}{superAdmin&&<Link href="/admin/utilisateurs" onClick={()=>setOpen(false)} className={`group flex items-center gap-3 rounded-[10px] px-3 py-2.5 text-[13px] font-medium transition ${path.startsWith('/admin/utilisateurs')?'bg-[#FCF108] text-[#2F2F2F] shadow-sm':'text-white/70 hover:bg-white/10 hover:text-white'}`}><UserCog size={17}/><span>Utilisateurs & accès</span></Link>}</nav>
   <div className="space-y-2 border-t border-white/10 p-4"><div className="rounded-xl bg-white/5 p-3 text-xs text-white/55"><span className="mb-1 block truncate font-semibold text-white/80">{auth?.user?.name||'Manager'}</span><span className="block text-[10px] font-semibold uppercase tracking-wider text-[#FCF108]/80">{roleLabel}</span></div><Link href="/logout" method="post" as="button" className="flex w-full items-center gap-3 rounded-[10px] px-3 py-2.5 text-left text-[13px] font-semibold text-white/70 transition hover:bg-[#BD2433] hover:text-white"><LogOut size={17}/><span>Déconnexion</span></Link></div>
  </aside>
  <div className="print:pl-0 lg:pl-[260px]"><header className="sticky top-0 z-20 flex h-[72px] items-center gap-4 border-b border-[#E8E7E2] bg-white/95 px-4 backdrop-blur print:hidden md:px-7"><button onClick={()=>setOpen(true)} className="rounded-lg p-2 hover:bg-gray-100 lg:hidden"><Menu size={21}/></button>{allowed('/modules/commandes')&&<form action="/modules/commandes" method="get" className="relative hidden max-w-sm flex-1 md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={17}/><input name="q" className="w-full rounded-xl border-0 bg-[#F5F5F2] py-2.5 pl-10 pr-3 text-sm focus:ring-2 focus:ring-[#BD2433]/20" placeholder="Rechercher une commande…"/></form>}<div className="ml-auto flex items-center gap-3">{allowed('/modules/rapports')&&<Link href="/modules/rapports" aria-label="Notifications" className="relative rounded-xl border border-gray-200 p-2.5 text-gray-500"><Bell size={18}/><i className="absolute right-2 top-2 size-1.5 rounded-full bg-[#BD2433]"/></Link>}<Link href="/profile" className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-gray-50"><span className="grid size-9 place-items-center rounded-xl bg-[#BD2433] text-sm font-bold text-white">{auth?.user?.name?.slice(0,2).toUpperCase()||'MI'}</span><span className="hidden text-left sm:block"><strong className="block text-xs">{auth?.user?.name||'Manager'}</strong><small className="text-[10px] text-gray-400">{roleLabel}</small></span><ChevronDown size={14} className="text-gray-400"/></Link></div></header><main className="p-4 print:p-0 md:p-7"><div className="mb-7 flex flex-wrap items-center justify-between gap-4 print:hidden"><div>{header}</div>{action}</div>{children}</main></div>
 </div>
}
